### ISSUE TITLE
Weird "invalid default" error for a constant

### ISSUE THREAD

**Issue by oflatt** [mwillsey/egg-smol#112]
Repro [here](https://www.mwillsey.com/egg-smol/?program=XQAAgAA5CgAAAAAAAAAUHMnnVi1HpjHqKTBMTl3K1d1VkvRLycV8acauPSanxg_Dvup06imKAhJXZ1-xOs74JWZ2goEApPAMZViekxRdOG-7fV5AQXDAGz9IBYif3gg7Um3RUxz9zmvnU8lmTh28Mlqs3KDeGEucTiY1PrQd8qX4hnK9e0MaC9R7Aeezln_e4kztPJlM7PqjmbhMt-syqUgfXB_p65qWeMf8sKMcFpNjDmbU6StJ6uMWLPJGCOEOPtmggi6rhiuXpSNagCMTZ9s2i-sqlrJ2jPilkdZsl0S5YL0vQl9EUFhYToI84slzR9GaFP6-a-TZR_tCtQZboWJb-4i-IQCNjKBNDYBrHf3WyJoFM-9hpD3yFPxq74QPE_jCnYHu7RGrmMQ7lCRFJxs6WsgCdIUCyaHzBAbzloAY8VYryulA0VrvXslCYKz1fhXot1UikCSs_gxMM1E7um1KdEcdmJ5ErqbSjR5Z-clbC7NrCWhvNY3CKJAxEeJfwKvVEQaWPj8X0Q4x0eL0POgqVt_Hll5ll3nJGAVbozYdV2UJQhPb-XcQ35y-tXhKcJ9_MgpM163rRbBbkMBfGgNRrRzXVB4nWUj5MISvfMU0Ss2zOy_aGiTdFKOQcseFZsBv72yeX4hd5Bj8IoVHNv_M0z5bOKEuVhJmAzzTGTmTJScxQb149EFvKr0pOX91dqhpssF6ukMiizla0J6-WwRIOxFECktfCvIzME12w4P_rqkKtsiLlP-ZflkCZ0VSv1QPY6ehHKYPcouii7_itwoz5z4bkiDnW_pAbYhi1WXv8bJqnFMcQuqTRqwa7r4FDkS-qmtSuK8f-XPhNMjDCEGn8wMKX5c9dr56azi3q_7epMdb-XoiEsR8g59IUh_RoyOjfQmYb2qYdfxifrX7KPHZkCxBnqbL-1IPYj8DuJPACo8mSByCKeN3ra9zekUfg2MLEdMm7Dv-uq8UpdbNKzKUPhVGbcoYx7pxE5WliArgZ4X8q5hW0URbsuw7hmSfZHr9d75CfzbwLu5obWeibGKD3qpeV3jCKibQEtPQvdM5oaVXEI0N__buuK8%253D)

**Comment by ezrosent** [comment]
This happens because the `clear` command also clears constants in `define`. `define`s are desugared to functions from 0-length vectors of values to their output, so any constant will just have whatever "default" value for its sort made up when it's used after a clear. There is no such default for integers, hence the error. I agree this behavior seems wrong, but I'm not sure what we should do instead.

One option here would be to have `clear` skip `define`s. But what happens if we have:

```
(datatype Expr
  (Lit i64)
  (Add Expr Expr))

(define x (Lit 0))
(define y (Lit 1))
(define z (Add x y))
```

Clearing `Expr` will remove the mapping for any ids in `x`, `y`, and `z`.

Seems like what we want to do instead is replay any `define`s after a clear. That won't always work, e.g.


```
(function SomeInt i64 i64)
(set (SomeInt 0) 1)
(define x (SomeInt 0))
```

Maybe we should ~always be using push and pop rather than clear?
