### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by philzook58** [mwillsey/egg-smol#13]
This variant of a program in tests is not doing what I expect.
```
(datatype Math
  (Num i64)
  (Var String)
  (Add Math Math))

(define start (Add (Num 3) (Add (Num 4) (Var 42)))) ;; TODO typecheck this!
(define goal  (Add (Num 7) (Var 42)))

(function depth (Math) (Min i64))

(rewrite (Add x y) (Add y x))
(rewrite (Add (Add x y) z) (Add x (Add y z)))
(rewrite (Add (Num x) (Num y)) (Num (+ x y)))

(rule ((= e (Num x)))  ((= 0 (depth e))))

(run 3)
(extract (Num 4))
(extract (depth (Num 4)))
; [ERROR] Not found: (depth (Num 4))
(check (= 0 (depth (Num 4))))
```
I'm not sure what I am missing here. Eventually, I'm trying to use lattice values for extraction.

**Comment by yihozhang** [comment]
There are two issues with this program:

1. `extract` only works for sort-valued relations.
2. `(rule ((= e (Num x)))  ((= 0 (depth e))))` currently is a no-op, because `=` is single directional and will assign values from the rest of the args to the first arg. After some discussions, I think we should make `=` bidirectional, i.e., all the assignable args should be assigned the same value.

**Comment by mwillsey** [comment]
Can we close this? 2 is now obsolete (can't do `=` in the actions), and 1 seems to be fundamental.

**Comment by yihozhang** [comment]
Sure. We don't need to care about 2 for now. For 1, I'm wondering how can we do extraction in the new IR? Do we need to design a new interface for it?
